# Generated by Django 4.2.1 on 2023-09-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyJobApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='comformpassword',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='password',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
