# Generated by Django 4.2.1 on 2023-09-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyJobApp', '0002_rename_lastname_student_comformpassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='job_images/')),
                ('postdescription', models.TextField()),
                ('people_required', models.IntegerField()),
                ('job_type', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
